template = "https://github.com/giellalt/template-lang-und"
rev_id = 287
template_sha = "15a8cf1917db1d48c56f7254ed58b4e74a6fcd9c"

[replacements]
__GLOTTOLOG_ID__ = "corn1251"
__REPO__ = "lang-cor"
__UND2C__ = "kw"
__UNDEFINED__ = "Cornish"
__UND__ = "cor"
