[package]
name = "cor"
human_name = "Cornish"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.cor]
filename = "kw-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-cor"
platform = "windows"
uuid = "4545B4D7-E474-47CD-81D1-99A7703ECEA1"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.kw"
package = "speller-cor"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-cor-mso"
platform = "windows"
uuid = "5A2E2DCA-5769-42FB-8D21-C005E4A32D0A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-cor"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
